splash = false

preload = /home/sam/Pictures/github_coding_images/Owl.png
preload = /home/sam/Pictures/github_coding_images/ChatGPT Owl.png
preload = /home/sam/Pictures/github_coding_images/Gemini Owl.png

wallpaper = HDMI-A-1,/home/sam/Pictures/github_coding_images/ChatGPT Owl.png
wallpaper = DP-1,/home/sam/Pictures/github_coding_images/Gemini Owl.png
wallpaper = DP-2,/home/sam/Pictures/github_coding_images/Owl.png
