splash = false

preload = ~/Pictures/github_coding_images/Owl.png
preload = ~/Pictures/github_coding_images/ChatGPT Owl.png
preload = ~/Pictures/github_coding_images/Gemini Owl.png

wallpaper = HDMI-A-1,~/Pictures/github_coding_images/ChatGPT Owl.png
wallpaper = DP-1,~/Pictures/github_coding_images/Gemini Owl.png
wallpaper = DP-2,~/Pictures/github_coding_images/Owl.png
wallpaper = eDP-1,~/Pictures/github_coding_images/Owl.png
