preload=/home/sam/Pictures/github_coding_images/Owl.png
wallpaper=HDMI-A-2,/home/sam/Pictures/github_coding_images/Owl.png
wallpaper=DP-1,/home/sam/Pictures/github_coding_images/Owl.png
wallpaper=DP-2,/home/sam/Pictures/github_coding_images/Owl.png
